version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest  # Use an appropriate base image
    steps:
      - checkout  # Checkout the code from GitHub

      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: docker build -t $DOCKER_LOGIN/my-app:latest .

      - run:
          name: Log in to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin

      - run:
          name: Push Docker Image
          command: docker push $DOCKER_LOGIN/my-app:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
