version: 2.1
jobs:
  build:
    docker:
    - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: node Demo.js
      - command: echo "Running..."

workflows:
  build:
    jobs:
      - build