version: 2.1

orbs:
  docker: circleci/docker@2.4.0  # Ensure correct Docker orb version

jobs:
  build-and-push:
    docker:
      - image: cimg/node:10.16.3  # Use any base image with Docker installed
    steps:
      - checkout  # Pull the latest code

      # Enable Docker-in-Docker
      - setup_remote_docker

      # Authenticate with Docker Hub
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin

      # Build Docker image
      - run:
          name: Build Docker Image
          command: docker build -t "$DOCKER_LOGIN"/simple_demo:latest .

      # Push Docker image to Docker Hub
      - run:
          name: Push Docker Image
          command: docker push "$DOCKER_LOGIN"/simple_demo:latest

workflows:
  build-and-deploy:
    jobs:
      - build-and-push
